-- Development settings (zai AI, dev OTP visible, payment simulation)
-- Generated by scripts/generate-seed-sql.ts — INSERT OR IGNORE (never clobbers live admin settings).

INSERT OR IGNORE INTO "Setting" ("id", "key", "value", "group", "updatedAt") VALUES ('setting-ai', 'ai', '{"provider":"zai","apiKey":"","model":""}', 'ai', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Setting" ("id", "key", "value", "group", "updatedAt") VALUES ('setting-sms', 'sms', '{"provider":"none","devMode":true}', 'sms', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Setting" ("id", "key", "value", "group", "updatedAt") VALUES ('setting-payment', 'payment', '{"merchantId":"","sandbox":true,"simulationMode":true}', 'payment', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Setting" ("id", "key", "value", "group", "updatedAt") VALUES ('setting-general', 'general', '{"restaurantName":"رستوران نخل","restaurantTagline":"طعم اصیل رفسنجان، با نوآوری هوش مصنوعی","address":"رفسنجان، بلوار شهید مطهری، نبش کوچه نخل، پلاک ۱۲","phone":"03434300000","email":"info@nakhl-rafsanjan.ir","workingHours":"همه روزه از ساعت ۱۲ ظهر تا ۱۲ شب","taxPercent":10,"deliveryFee":35000,"minOrderAmount":100000,"freeDeliveryOver":500000,"city":"رفسنجان","instagram":"nakhl.rafsanjan","telegram":"nakhl_restaurant"}', 'general', CURRENT_TIMESTAMP);
