/**
 * Nakhl Restaurant — D1 seed SQL generator
 * -----------------------------------------
 * Reads prisma/seed-data.json and emits plain SQL files for Cloudflare D1
 * (applied with `wrangler d1 execute DB --local|--remote --file ...`):
 *
 *   seed/seed-core.sql      — categories, menu items, coupons, admin user
 *                             (idempotent: INSERT OR IGNORE on unique keys)
 *   seed/settings-dev.sql   — development settings (zai AI, dev OTP, payment
 *                             simulation — for the local Miniflare D1)
 *   seed/settings-prod.sql  — production-safe settings (openrouter, no dev
 *                             OTP, real ZarinPal — for the remote D1)
 *
 * Run:  bun scripts/generate-seed-sql.ts
 * (Regenerating produces a fresh random scrypt salt for the admin password.)
 */
import crypto from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import seedData from "../prisma/seed-data.json" with { type: "json" };

type Row = Record<string, unknown>;

const ADMIN_USERNAME = process.env.ADMIN_USERNAME || "rayantech";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "Hasan78484@";
const ADMIN_DISPLAY_NAME = "مدیر رستوران نخل";

/** SQL string literal with proper escaping. */
function sqlStr(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlBool(value: boolean | undefined, fallback = false): string {
  return (value ?? fallback) ? "1" : "0";
}

function sqlInt(value: number | null | undefined, fallback: number | null = null): string {
  if (value === null || value === undefined) {
    return fallback === null ? "NULL" : String(fallback);
  }
  return String(value);
}

/** Mirrors src/lib/auth.ts scrypt scheme: `salt:hash` (hex). */
function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16).toString("hex");
  const hash = crypto.scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${hash}`;
}

function valueList(values: string[]): string {
  return `(${values.join(", ")})`;
}

const lines: string[] = [];
lines.push("-- Nakhl Restaurant — core seed (categories, menu, coupons, admin)");
lines.push("-- Generated by scripts/generate-seed-sql.ts — idempotent (INSERT OR IGNORE).");
lines.push("");
lines.push("PRAGMA foreign_keys = ON;");
lines.push("");

// ---------- categories ----------
lines.push("-- ===== Categories =====");
for (const c of seedData.categories as Row[]) {
  lines.push(
    `INSERT OR IGNORE INTO "Category" ("id", "name", "slug", "icon", "sortOrder", "isActive") VALUES ${valueList([
      sqlStr(c.id as string),
      sqlStr(c.name as string),
      sqlStr(c.slug as string),
      sqlStr((c.icon as string | null) ?? null),
      sqlInt(c.sortOrder as number | undefined, 0),
      sqlBool(c.isActive as boolean | undefined, true),
    ])};`,
  );
}
lines.push("");

// ---------- menu items ----------
lines.push("-- ===== Menu items =====");
for (const i of seedData.items as Row[]) {
  const gallery = i.gallery ? JSON.stringify(i.gallery) : null;
  lines.push(
    `INSERT OR IGNORE INTO "MenuItem" ("id", "name", "description", "price", "categoryId", "imageUrl", "gallery", "isAvailable", "isSpecial", "isDrink", "isVegetarian", "isSpicy", "calories", "prepTime", "ingredients", "sortOrder", "orderCount", "updatedAt") VALUES ${valueList([
      sqlStr(i.id as string),
      sqlStr(i.name as string),
      sqlStr((i.description as string | null) ?? null),
      sqlInt(i.price as number, 0),
      sqlStr(i.categoryId as string),
      sqlStr((i.imageUrl as string | null) ?? null),
      sqlStr(gallery),
      sqlBool(i.isAvailable as boolean | undefined, true),
      sqlBool(i.isSpecial as boolean | undefined, false),
      sqlBool(i.isDrink as boolean | undefined, false),
      sqlBool(i.isVegetarian as boolean | undefined, false),
      sqlBool(i.isSpicy as boolean | undefined, false),
      sqlInt((i.calories as number | null) ?? null),
      sqlInt((i.prepTime as number | null) ?? null),
      sqlStr((i.ingredients as string | null) ?? null),
      sqlInt((i.sortOrder as number | undefined) ?? 0, 0),
      sqlInt((i.orderCount as number | undefined) ?? 0, 0),
      "CURRENT_TIMESTAMP",
    ])};`,
  );
}
lines.push("");

// ---------- coupons ----------
lines.push("-- ===== Coupons =====");
for (const c of seedData.coupons as Row[]) {
  lines.push(
    `INSERT OR IGNORE INTO "Coupon" ("id", "code", "title", "type", "value", "minOrder", "maxDiscount", "usageLimit", "usedCount", "perUserLimit", "startsAt", "expiresAt", "isActive", "updatedAt") VALUES ${valueList([
      sqlStr(c.id as string),
      sqlStr(c.code as string),
      sqlStr(c.title as string),
      sqlStr(c.type as string),
      sqlInt(c.value as number, 0),
      sqlInt((c.minOrder as number | undefined) ?? 0, 0),
      sqlInt((c.maxDiscount as number | null) ?? null),
      sqlInt((c.usageLimit as number | undefined) ?? 0, 0),
      sqlInt(0),
      sqlInt((c.perUserLimit as number | undefined) ?? 1, 1),
      sqlStr((c.startsAt as string | null) ?? null),
      sqlStr((c.expiresAt as string | null) ?? null),
      sqlBool((c.isActive as boolean | undefined) ?? true, true),
      "CURRENT_TIMESTAMP",
    ])};`,
  );
}
lines.push("");

// ---------- admin ----------
lines.push("-- ===== Admin user =====");
lines.push(`-- username: ${ADMIN_USERNAME}${ADMIN_PASSWORD === "Hasan78484@" ? " (DEFAULT password — change it from the admin panel immediately!)" : ""}`);
lines.push(
  `INSERT OR IGNORE INTO "AdminUser" ("id", "username", "passwordHash", "displayName", "failedAttempts") VALUES ${valueList([
    sqlStr("admin-seed-root"),
    sqlStr(ADMIN_USERNAME),
    sqlStr(hashPassword(ADMIN_PASSWORD)),
    sqlStr(ADMIN_DISPLAY_NAME),
    sqlInt(0),
  ])};`,
);
lines.push("");

mkdirSync("seed", { recursive: true });
writeFileSync("seed/seed-core.sql", `${lines.join("\n")}\n`, "utf8");

// ---------- settings ----------
const GENERAL_SETTINGS = {
  restaurantName: "رستوران نخل",
  restaurantTagline: "طعم اصیل رفسنجان، با نوآوری هوش مصنوعی",
  address: "رفسنجان، بلوار شهید مطهری، نبش کوچه نخل، پلاک ۱۲",
  phone: "03434300000",
  email: "info@nakhl-rafsanjan.ir",
  workingHours: "همه روزه از ساعت ۱۲ ظهر تا ۱۲ شب",
  taxPercent: 10,
  deliveryFee: 35000,
  minOrderAmount: 100000,
  freeDeliveryOver: 500000,
  city: "رفسنجان",
  instagram: "nakhl.rafsanjan",
  telegram: "nakhl_restaurant",
};

function settingsSql(
  fileName: string,
  header: string,
  values: { key: string; group: string; value: Row }[],
): void {
  const out = [
    `-- ${header}`,
    "-- Generated by scripts/generate-seed-sql.ts — INSERT OR IGNORE (never clobbers live admin settings).",
    "",
    ...values.map(
      (g) =>
        `INSERT OR IGNORE INTO "Setting" ("id", "key", "value", "group", "updatedAt") VALUES ${valueList([
          sqlStr(`setting-${g.key}`),
          sqlStr(g.key),
          sqlStr(JSON.stringify(g.value)),
          sqlStr(g.group),
          "CURRENT_TIMESTAMP",
        ])};`,
    ),
  ];
  writeFileSync(fileName, `${out.join("\n")}\n`, "utf8");
}

settingsSql("seed/settings-dev.sql", "Development settings (zai AI, dev OTP visible, payment simulation)", [
  { key: "ai", group: "ai", value: { provider: "zai", apiKey: "", model: "" } },
  { key: "sms", group: "sms", value: { provider: "none", devMode: true } },
  { key: "payment", group: "payment", value: { merchantId: "", sandbox: true, simulationMode: true } },
  { key: "general", group: "general", value: GENERAL_SETTINGS },
]);

settingsSql("seed/settings-prod.sql", "Production-safe settings (OpenRouter, no dev OTP, real ZarinPal)", [
  // "zai" provider only exists inside the z.ai sandbox — production uses
  // OpenRouter (API key configured later in the admin panel).
  { key: "ai", group: "ai", value: { provider: "openrouter", apiKey: "", model: "" } },
  { key: "sms", group: "sms", value: { provider: "none", devMode: false } },
  { key: "payment", group: "payment", value: { merchantId: "", sandbox: false, simulationMode: false } },
  { key: "general", group: "general", value: GENERAL_SETTINGS },
]);

console.log("✔ wrote seed/seed-core.sql, seed/settings-dev.sql, seed/settings-prod.sql");
