/**
 * Nakhl Restaurant — custom Cloudflare Worker entry
 * -------------------------------------------------
 * `wrangler.jsonc` points `main` here. This entry:
 *
 *   1. re-exports the Durable Object class (required: DO classes must be
 *      exported from the worker's main module), and
 *   2. routes WebSocket upgrade requests for `/api/ws` straight to the
 *      `NakhlRealtime` Durable Object BEFORE the OpenNext/Next.js handler —
 *      the 101 Switching Protocols response cannot pass through the Next.js
 *      request pipeline, so the upgrade must be answered at the worker edge.
 *
 * Everything else is delegated to the OpenNext worker generated by
 * `bun run cf:build` at `.open-next/worker.js`.
 */
import baseWorker from "../.open-next/worker.js";
import { NakhlRealtime } from "./do/realtime";

export { NakhlRealtime };

const REALTIME_WS_PATH = "/api/ws";

/**
 * @param {Request} request
 * @param {{ REALTIME?: { idFromName(name: string): unknown; get(id: unknown): { fetch(input: RequestInfo, init?: RequestInit): Promise<Response> } } }} env
 * @param {unknown} ctx
 */
const worker = {
  async fetch(request, env, ctx) {
    if (env.REALTIME) {
      const url = new URL(request.url);
      if (
        url.pathname === REALTIME_WS_PATH &&
        (request.headers.get("upgrade") || "").toLowerCase() === "websocket"
      ) {
        // Forward the upgrade request to the singleton realtime object.
        const id = env.REALTIME.idFromName("global");
        const stub = env.REALTIME.get(id);
        return stub.fetch(request);
      }
    }
    return baseWorker.fetch(request, env, ctx);
  },
};

export default worker;
